### ISSUE TITLE
macOS - pasting a long content makes the action bars disappear 

### ISSUE THREAD

**Issue by JodyZ0203** [Bistard/MarkdownNote#9]
**Describe the bug**
When I paste in multiple images or a large image, the action bar will get pushed up, which makes it disappear.
**To Reproduce**
1. Paste in a long string of characters or images
2. Observe how the action bar is invisible

**Expected behavior**
Action Bar should remain still
**Screenshots**
<img width="1203" alt="Screen Shot 2021-08-22 at 12 26 46 AM" src="https://user-images.githubusercontent.com/56443135/130342283-ac1aa522-32ff-45c2-8415-87236ee0087f.png">
<img width="641" alt="Screen Shot 2021-08-22 at 1 42 27 AM" src="https://user-images.githubusercontent.com/56443135/130343905-4f104274-25ce-457d-a276-e5edce8a74e7.png">

**Additional comments**
Not Sure if this is on Windows or Linux

**Comment by Bistard** [comment]
This issue not only happens when inserting images but also every time when the content exceeds the height of the window, the bug happens. Fixed here 52dea70c933ded90523602b92489631fe7d038ec.
